### PR TITLE
Sign in with Slack + Private team page

### PR DESCRIPTION
**Pull request by davb**
Added Sign-in with Slack based on the following (required) env vars:
```
# from the mangrove-website Slack app, ask me for access
SLACK_CLIENT_ID, SLACK_CLIENT_SECRET
# comma-separated list of Slack teams that are allowed for sign-in
SLACK_TEAM_IDS=<team ID>
# a secret string to secure cookies and sign-in
SECRET
```

Also changed the Team page to display an embedded Airtable view.
When signed in, the Team page displays a different Airtable view with more detail.

### CODE REVIEW

**Comment by ghost** [comment]
group

I have to manually sign in to the mangrove slack if I want to connect my account with it
I'm not sure how to do it with passport, but you can target a specific team to avoid this:

image

from https://api.slack.com/docs/oauth

**Comment by ghost** [comment]
If we can't restrict the workspace, we could display a modal like this before the redirection
 
modal

**Comment by davb** [comment]
thanks @tchret for the feedback!
The `?team` param is correctly set [here](https://github.com/MeetMangrove/mangrove-website/pull/32/files#diff-567284bb08dc023ac92bad5d592343feR10). I was able to confirm that Passport is passing the value to Slack, but Slack appears to completely ignore it (!)

That is easy to verify by navigating to the following URL (which does contain `?team`):
```
https://slack.com/oauth/authorize?team=mangrove&response_type=code&redirect_uri=https%3A%2F%2Fmangrovewebsite-pr-32.herokuapp.com%2Fauth%2Fslack%2Fcallback&scope=identity.basic%20identity.email%20identity.avatar%20identity.team&client_id=19445422710.261631907779
```

I'll try to look more online and/or reach out to Slack to see what we can do.
The modal you suggest is a good idea but it does add one step to the process. To begin with I suggest putting that explanation in an error message we'd show after the user has tried to sign in with the wrong team, which we currently reject without much explanation (see [here](https://github.com/MeetMangrove/mangrove-website/pull/32/files#diff-0364f57fbff2fabbe941ed20c328ef1aR61))

I also propose extending the [session duration](https://github.com/MeetMangrove/mangrove-website/pull/32/files#diff-0364f57fbff2fabbe941ed20c328ef1aR28) from 24 hours to something like 30 days so that at least people don't have to go through this too often!

**Comment by ghost** [comment]
@davb: It's no mangrove.slack.com but mangroveteam.slack.com 😛
`team=mangroveteam` 

I even think they ask the team ID:
`team=T0KD3CELW` (got it from the slack source code)

--------------

```
The modal you suggest is a good idea but it does add one step to the process. To begin with I suggest putting that explanation in an error message we'd show after the user has tried to sign in with the wrong team, which we currently reject without much explanation (see here)
```

better indeed! I can do the design+integration of this page if the team restriction doesn't work

**Comment by davb** [comment]
@tchret good catch! Just switched from team name to the team ID and it now works; it seems it's picking up the right team now. The error page is still necessary though for all cases when users will not notice and authorize with the wrong team. I suggest we do that in a separate PR so we can merge this one.

**Pull request merged**
