### PR TITLE
Team page max 20 random friends

### PR DESCRIPTION
**Pull request by Jauny**
This resolves issue #3 

Some quick boilerplate for the team's page. Can definitely be made better, but wanted to push in at least a light boilerplate so anyone can biggy back on it;

- [x] I'm sure the script can be cleaned up a little
- [x] a blurr in/out animation for change of members would be nice.
- [x] Avoid dups in first 20 friends but not when adding a new friend.

### CODE REVIEW

**Comment by Jauny** [comment]
did some cleanup, the fadein/out, etc. That might be good for production now :)

friends list

**Comment by AmbroiseCollon** [comment]
Thank you very much for your work @Jauny !

If I understand correctly, here is what you do :
1/ You create a list of 20 friends
2/ Every 5 seconds, you pick one random friend by making sure he's not already in the 20 visible
3/ You animate the change removing a random picked visible friend

The only problem I see with this approach is that a person can be shown twice in a very short period of time 10s. And it will not reflect the size and diversity of Mangrove friends.

Here is what I suggest :
1/ In init : 
 \- You randomize the whole array of friends
 \- You present the 20 first elements
2/ When swapping 
 \- You remove a random person from the 20 first friends (the visible ones)
 \- This removed friend is pushed at the end of the whole friends array
 \- You replace him with the friend in position 21st in the whole array

This prevents someone from being presenting too often while keeping the randomness both on screen (where next animation takes place) and in friends (the order of presented friends are still random).

I completely understand if you don't have time to do the change. I can take it on from now if you wish, based on your structure. I just wanted to give you the opportunity to fully ship the feature ! Many thanks either way !

**Comment by Jauny** [comment]
that makes sense. Not sure when I'll have time to fix this - feel free to take over if you want this to be shipper earlier than later. 
If you don't, I'll try to fix this before EOW.

**Comment by Jauny** [comment]
@AmbroiseCollon ok I did have some time to do it tonight, thanks for the suggestion that pushed me in cleaning up things!

So here's what I do now

- randomize friends list
- get the 20 first friends and set my next friends index at 20
- every 5 seconds, remove a random friends for the div, add the next friends, set next friends index at 21.
- I use modulo (%) to make sure the "nextFriendIndex" starts over at 0 once it reaches the last friends in the list.

Let me know what you think :)

**Comment by AmbroiseCollon** [comment]
C'est merge merci !

**Pull request merged**
